"""Write a checklist of everything the web archive could not supply.

Regenerated on every build so it always describes what is actually deployed,
rather than drifting away from it. `stage.py` calls `write()` at the end of a
run.

Pages that are withheld on purpose -- the forum, wallpapers, tools, live chat,
the firewall page -- are excluded, because their absence is a decision rather
than a gap.
"""

import collections
import os
import posixpath
import re

HREF_RE = re.compile(r"<a[^>]+href=(?:\"([^\"]*)\"|'([^']*)')", re.I)

# Absent by choice, not by accident.
INTENTIONAL = ("forum/", "wiki/wallpapers", "wiki/tools",
               "chat.php", "download_firewall")


def _broken_links(dst, staged, candidates):
    broken = collections.Counter()
    for rel in sorted(staged):
        if not rel.endswith((".html", ".htm")):
            continue
        full = os.path.join(dst, rel.replace("/", os.sep))
        if not os.path.isfile(full):
            continue
        with open(full, "r", encoding="utf-8", errors="replace") as fh:
            text = fh.read()
        base = posixpath.dirname(rel)
        for dq, sq in HREF_RE.findall(text):
            url = dq or sq
            cands = candidates(url, base)
            if not cands or any(c in staged for c in cands):
                continue
            target = cands[0]
            if not target.startswith(INTENTIONAL):
                broken[target] += 1
    return broken


def write(path, image_todos, dst, staged, candidates):
    """image_todos maps an img src to the list of pages it appears on."""
    broken = _broken_links(dst, staged, candidates)

    lines = [
        "# Content the web archive could not supply",
        "",
        "Generated by `stage.py` on every build. Do not edit by hand.",
        "",
        "Pages withheld on purpose (the forum, wallpapers, tools, live chat,",
        "the firewall page) are not listed here: those are decisions, not gaps.",
        "",
        "## Missing images (%d)" % len(image_todos),
        "",
        "Each of these renders on the site as a dashed red `[ ] missing image`",
        "marker naming the file, so they can be found while browsing.",
        "",
    ]
    for src, pages in sorted(image_todos.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        lines.append("- [ ] `%s`" % src[:160])
        lines.append("  - %d place(s), e.g. `%s`" % (len(pages), pages[0]))

    lines += [
        "",
        "## Broken links (%d targets, %d references)" % (
            len(broken), sum(broken.values())),
        "",
        "These resolve to pages the crawler never captured. Most are wiki",
        "sub-pages and DokuWiki image-detail viewers.",
        "",
    ]
    for target, n in broken.most_common():
        lines.append("- [ ] `%s` — %d reference(s)" % (target[:160], n))

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    return len(image_todos), len(broken), sum(broken.values())
