"""
make_single_player_galaxy.py , build the galaxy the launcher's Single Player
mode ships
===========================================================================
    python make_single_player_galaxy.py                 # writes client\\SinglePlayerGalaxy.dat
    python make_single_player_galaxy.py --out other.dat
    python make_single_player_galaxy.py --keep-open     # leave the result running

Generates a fresh TestBed galaxy, saves it at turn 0, gives the AI civ the ship
designs it cannot create for itself, and writes the result as a `.dat` the
client can be launched on directly.

REQUIREMENTS. The stub server must be running , the save goes out over HTTP and
is captured server-side. Either leave the launcher open or run run_server.ps1.
"""
import argparse
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
CLIENT_DIR = os.path.dirname(HERE)
REPO = os.path.dirname(CLIENT_DIR)

sys.path.insert(0, os.path.join(HERE, "ai_player"))
sys.path.insert(0, os.path.join(REPO, "server", "dev_tools"))

EXE = os.path.join(CLIENT_DIR, "CosmicSupremacy_TestBed.exe")
PASS_FILE = os.path.join(CLIENT_DIR, "TestBedGalaxy_local.csgalaxy")
DEFAULT_OUT = os.path.join(CLIENT_DIR, "SinglePlayerGalaxy.dat")

# Where a savegame POST lands. The launcher points CS_DATA_DIR at release\data,
# run_server.ps1 leaves it at server\ , so look in both and take the newest
# rather than making the caller remember which server they started.
SAVE_DIRS = [os.path.join(REPO, "server", "saves"),
             os.path.join(REPO, "release", "data", "saves")]

# The AI civ. The human's civ name comes from the .csgalaxy pass token
# ('DemoPlayer'); this one is generated by the engine.
AI_CIV = "BadGuy"

# probe1 is legal on turn 0 , chassis 0, scanner 0 and engine 0 all come from
# the two starting techs, so Explore works from the first turn instead of
# waiting on a design that never arrives. f1 and b1 carry weapons, which nothing
# grants until Cold Fusion (id 3), so they sit in the list unbuildable until the
# AI researches its way to them.
#
# Two engines on the scout and one on the warships: a scout is a chassis and
# engines and nothing else (STRATEGY.md §4.1), while a warship's speed is a
# known open problem and not one to fix by quietly overspending here.
#
# A SCANNER IS REQUIRED on every design. A synthesised hull without one crashed
# the client at the turn boundary when the build completed and the engine tried
# to construct the ship , and it queued and built perfectly happily up to that
# point, which is what made it look fine.
DESIGNS = [
    ("probe1", {"chassis": [0], "scanners": [0], "engines": [0, 0]}),
    ("f1",     {"chassis": [0], "scanners": [0], "engines": [0], "weapons": [0]}),
    ("b1",     {"chassis": [0], "scanners": [0], "engines": [0], "weapons": [10]}),
]


def log(msg):
    print(msg, flush=True)


def client_pids():
    """Every running client. Excludes the launcher, which shares the prefix."""
    out = subprocess.run(
        ["powershell", "-NoProfile", "-Command",
         "Get-Process -Name 'CosmicSupremacy*' -ErrorAction SilentlyContinue "
         "| Where-Object { $_.ProcessName -ne 'CosmicSupremacyLauncher' } "
         "| Select-Object -ExpandProperty Id"],
        capture_output=True, text=True).stdout
    return [int(x) for x in out.split() if x.strip().isdigit()]


def close_client(timeout=20):
    pids = client_pids()
    if not pids:
        return
    for pid in pids:
        subprocess.run(["powershell", "-NoProfile", "-Command",
                        f"Stop-Process -Id {pid} -Force"], capture_output=True)
    deadline = time.time() + timeout
    while time.time() < deadline:
        if not client_pids():
            log(f"  closed client (pid {', '.join(map(str, pids))})")
            return
        time.sleep(0.5)
    raise SystemExit("the client would not exit")


def launch(arg, timeout=120):
    """Start the client on a pass file or a .dat, and wait until it is readable.

    Waiting on the STATE rather than on a timer: a load that takes 40 seconds
    and a load that crashed look identical for the first 39.
    """
    if client_pids():
        raise SystemExit("a client is already running; close it first , "
                         "launching a second silently kills the first")
    log(f"  launching on {os.path.basename(arg)}")
    subprocess.Popen([EXE, arg], cwd=CLIENT_DIR,
                     creationflags=getattr(subprocess, "DETACHED_PROCESS", 0))
    import gamestate as gs
    deadline = time.time() + timeout
    while time.time() < deadline:
        if not client_pids():
            time.sleep(0.5)
            continue
        try:
            snap = gs.Snapshot()
            if snap.civs and len(snap.suns) > 10:
                log(f"  up: turn {snap.turn}, {len(snap.suns)} suns, "
                    f"civs {[c.civ_name for c in snap.civs]}")
                return snap
        except Exception:
            pass
        time.sleep(1.0)
    raise SystemExit(f"client did not become readable within {timeout}s")


def newest_capture(since):
    """The newest .b64 written after `since`, across both server layouts."""
    best = None
    for d in SAVE_DIRS:
        if not os.path.isdir(d):
            continue
        for name in os.listdir(d):
            if not name.endswith(".b64"):
                continue
            path = os.path.join(d, name)
            mtime = os.path.getmtime(path)
            if mtime >= since and (best is None or mtime > best[0]):
                best = (mtime, path)
    return best[1] if best else None


def capture_save(name="spseed"):
    started = time.time() - 1
    r = subprocess.run([sys.executable, os.path.join(HERE, "trigger_save.py"),
                        "--name", name[:15]],
                       capture_output=True, text=True, cwd=HERE)
    if "saved" not in r.stdout:
        log(r.stdout + r.stderr)
        raise SystemExit("SaveGame did not report success")
    path = newest_capture(started)
    if not path:
        raise SystemExit(
            "SaveGame succeeded but no capture appeared in " +
            " or ".join(SAVE_DIRS) +
            " , the stub server has to be running for the POST to be stored. "
            "Leave the launcher open, or start run_server.ps1.")
    log(f"  captured {os.path.basename(path)}")
    return path


def seed(capture, out_dat):
    import save_parser as sp
    import inject_design as idg
    import game_cycle as gc

    blob = sp.decode_save(open(capture).read())
    targets = dict((n, i) for n, i in gc.civ_template_ids(blob))
    log(f"  civs in the blob: {sorted(targets)}")
    if AI_CIV not in targets:
        raise SystemExit(
            f"no civ named {AI_CIV!r} in the capture (saw {sorted(targets)}). "
            f"The engine names the rival civ, so a galaxy that names it "
            f"something else needs AI_CIV updated here AND the launcher's "
            f"manifest entry changed to match.")

    # Injecting shifts every offset behind it, but object IDS are stable and
    # that is what inject_design keys on , so the template id resolved once up
    # front stays correct across all three insertions.
    tid = targets[AI_CIV]
    for name, parts in DESIGNS:
        parts = dict(parts)
        parts.setdefault("list6", [])
        blob = idg.make(blob, tid, name, parts, None, log=lambda m: None)
        log(f"  seeded {name!r} for {AI_CIV!r}")

    blob = fix_player_civ_id(blob)

    with open(out_dat, "wb") as fh:
        fh.write(blob)
    log(f"  wrote {out_dat} ({len(blob)} bytes)")


def fix_player_civ_id(blob):
    """Give the human civ a non-zero Owner:4, or it is never empire-ticked.

    THIS IS THE BUG v0.1 SHIPPED. Owner:4 is the last u32 of an OWNR payload,
    and zero is a sentinel meaning "not simulated on this client" , the engine
    skips the whole empire-level half of the turn for that civ. Research
    (Owner:12), Owner:24 and the score (Owner:28) never move, while cash keeps
    ticking, so from inside the game the empire looks alive and the tech tree is
    simply unreachable for the entire game.

    Every galaxy generated through the TestBed pass token carries 0 here for the
    human civ, and this generator uses that token, so the fault is not
    incidental to one build , it is produced fresh every time this script runs.
    Confirmed causal on a live galaxy by an A/B differing only in these four
    bytes; see docs/CosmicSupremacy_Memory_Reconstruction_Report.md,
    "Research/science accrual".

    The lowest unused positive id, which reproduces the 20/21 pairing every
    healthy generated galaxy shows rather than inventing a third number.
    """
    import struct
    sys.path.insert(0, os.path.join(REPO, "server", "dev_tools"))
    import inject_civ as icv

    owners = icv.owner_records(blob)
    ids = {o["name"]: struct.unpack_from("<I", blob, o["end"] - 4)[0]
           for o in owners}
    log(f"  Owner:4 per civ: {ids}")
    broken = [o for o in owners
              if struct.unpack_from("<I", blob, o["end"] - 4)[0] == 0]
    if not broken:
        log("  every civ already has a non-zero Owner:4")
        return blob

    buf = bytearray(blob)
    taken = {v for v in ids.values() if v}
    for o in broken:
        uid = next(i for i in range(20, 256) if i not in taken)
        taken.add(uid)
        struct.pack_into("<I", buf, o["end"] - 4, uid)
        log(f"  {o['name']}: Owner:4 0 -> {uid}  "
            f"(0 means the engine would never tick its research or score)")
    return bytes(buf)


def verify(snap):
    """Both halves of the contract: the AI has the designs, the player does not."""
    import research
    ok = True
    for civ in snap.civs:
        mine = sorted(d.design_name for d in snap.designs
                      if d.owner is not None and d.owner.addr == civ.addr)
        log(f"  {civ.civ_name!r}: {mine}")
        seeded = {n for n, _ in DESIGNS}
        have = seeded & set(mine)
        if civ.civ_name == AI_CIV and have != seeded:
            log(f"    [!] missing {sorted(seeded - have)}")
            ok = False
        if civ.civ_name != AI_CIV and have:
            log(f"    [!] the human civ was seeded with {sorted(have)} , "
                f"it should own only what the engine gave it")
            ok = False

    # The point of seeding is designs the AI may build LATER, not now. Say which
    # is which, so a galaxy that accidentally starts the AI armed is visible
    # here rather than in a player's first game.
    ai = next((c for c in snap.civs if c.civ_name == AI_CIV), None)
    if ai is not None:
        done = {t for t, _ in ai.completed}
        for d in snap.designs:
            if d.owner is None or d.owner.addr != ai.addr:
                continue
            missing = research.explain_illegal(d, done)
            log(f"    {d.design_name!r:10} "
                + ("buildable now" if research.design_legal(d, done)
                   else f"locked until researched: {missing}"))

    # Read back from the LIVE galaxy, not from the blob fix_player_civ_id just
    # wrote. A value that is correct on disk and zero in memory would mean the
    # engine overwrites it at load, and that is the failure this has to catch.
    seen = {}
    for civ in snap.civs:
        uid = civ.u32(4)
        seen.setdefault(uid, []).append(civ.civ_name)
        if not uid:
            log(f"  [!] {civ.civ_name!r} has Owner:4 = 0, so the engine will "
                f"never tick its research or its score. This galaxy is the "
                f"v0.1 research bug; do not ship it.")
            ok = False
    for uid, names in seen.items():
        if uid and len(names) > 1:
            log(f"  [!] {names} share Owner:4 = {uid}; the score list holds one "
                f"row per distinct value, so one of them is invisible")
            ok = False
    log(f"  Owner:4 live: "
        + ", ".join(f"{c.civ_name}={c.u32(4)}" for c in snap.civs))
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--keep-open", action="store_true",
                    help="leave the verified galaxy running")
    a = ap.parse_args()

    for path in (EXE, PASS_FILE):
        if not os.path.exists(path):
            raise SystemExit(f"missing: {path}")

    log("1. generating a fresh galaxy")
    close_client()
    snap = launch(PASS_FILE)
    if snap.turn != 0:
        log(f"  [!] galaxy came up on turn {snap.turn}, not 0 , seeding it "
            f"anyway, but the shipped galaxy should start at turn 0")

    log("2. saving it")
    capture = capture_save()

    log("3. seeding the AI's designs")
    close_client()
    seed(capture, a.out)

    log("4. verifying the result loads")
    snap = launch(a.out)
    ok = verify(snap)

    if not a.keep_open:
        close_client()
    log("\n" + ("done , " + a.out if ok else "FAILED verification"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
